/** Adapter conformance fixtures and verifiers for document-graph implementors. */
export {
  GraphTopologyStoreConformanceLawSchema,
  GraphTopologyStoreConformanceViolation,
  makeGraphTopologyStoreConformanceFixture,
  makeProjectionIndexStoreConformanceFixture,
  makeSearchStoreConformanceFixture,
  ProjectionIndexStoreConformanceLawSchema,
  ProjectionIndexStoreConformanceViolation,
  SearchStoreConformanceLawSchema,
  SearchStoreConformanceViolation,
  verifyDocumentGraphStorageConformance,
  verifyGraphTopologyStoreConformance,
  verifyProjectionIndexStoreConformance,
  verifySearchStoreConformance,
  verifySemanticSearchStoreConformance,
  verifyTextSearchStoreConformance,
  type DocumentGraphStorageConformanceReport,
  type GraphTopologyStoreConformanceFixture,
  type GraphTopologyStoreConformanceLaw,
  type GraphTopologyStoreConformanceReport,
  type ProjectionIndexStoreConformanceFixture,
  type ProjectionIndexStoreConformanceLaw,
  type ProjectionIndexStoreConformanceReport,
  type SearchStoreConformanceFixture,
  type SearchStoreConformanceLaw,
  type SearchStoreConformanceReport,
} from "./conformance/search-store-conformance.js"
