/** Adapter conformance fixtures and verifiers for document-graph implementors. */
export {
  GraphRelationStoreConformanceLawSchema,
  GraphRelationStoreConformanceViolation,
  makeGraphRelationStoreConformanceFixture,
  makeProjectionIndexStoreConformanceFixture,
  makeSearchStoreConformanceFixture,
  ProjectionIndexStoreConformanceLawSchema,
  ProjectionIndexStoreConformanceViolation,
  SearchStoreConformanceLawSchema,
  SearchStoreConformanceViolation,
  verifyDocumentGraphStorageConformance,
  verifyGraphRelationStoreConformance,
  verifyProjectionIndexStoreConformance,
  verifySearchStoreConformance,
  verifySemanticSearchStoreConformance,
  verifyTextSearchStoreConformance,
  type DocumentGraphStorageConformanceReport,
  type GraphRelationStoreConformanceFixture,
  type GraphRelationStoreConformanceLaw,
  type GraphRelationStoreConformanceReport,
  type ProjectionIndexStoreConformanceFixture,
  type ProjectionIndexStoreConformanceLaw,
  type ProjectionIndexStoreConformanceReport,
  type SearchStoreConformanceFixture,
  type SearchStoreConformanceLaw,
  type SearchStoreConformanceReport,
} from "./conformance/search-store-conformance.js"
